- hosts: demo
  sudo: yes
  remote_user: ubuntu
  gather_facts: no
  pre_tasks:
    - name: 'install python-apt python3-apt aptitude'
      raw: sudo apt-get update; apt-get -y install python-apt python3-apt aptitude
  tasks:
    - name: 'install nginx'
      apt:
        name: nginx
        state: latest
        update_cache: yes
